dir.create("/Users/YanYang/code/Electric power consumption")
setwd("/Users/YanYang/code/Electric power consumption")
url <- c("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip")
download.file(url, destfile = "/Users/YanYang/code/Electric power consumption/electric_power_consumption.zip", method = "curl")
unzip("/Users/YanYang/code/Electric power consumption/electric_power_consumption.zip")
data <- read.table("household_power_consumption.txt", header = TRUE, sep = ";", na.strings = "?")

library(dplyr)
data2 <- mutate(data, Date = paste(data$Date, data$Time))
data2 <- select(data2, -Time)
data3 <- mutate(data2, Date = as.POSIXct(data2$Date))
use <- subset(data3, subset=(Date >= "2007-02-01 00:00:00" & Date <= "2007-02-02 23:59:00"))
plot(x = use$Date, y = use$Global_active_power, ylab = "Global Active Power (kilowatts)", xlab = "", type = "l")
dev.copy(png, file = "plot2.png", height = 480, width = 480)
dev.off()